services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-super
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      # KUNCI UTAMA: Memungkinkan Jenkins mengontrol Docker di host
      - /var/run/docker.sock:/var/run/docker.sock 
    user: root # Agar bisa akses docker.sock dengan mudah
    restart: unless-stopped

volumes:
  jenkins_home: